FROM node:22-alpine AS base
WORKDIR /app

FROM base AS deps

COPY package.json yarn.lock* ./
RUN yarn --frozen-lockfile

FROM base AS build
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN yarn build

FROM nginx:stable-alpine AS runner

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]